import{a as q,S as v,i as c}from"./assets/vendor-DqB7j7Ix.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const B="https://pixabay.com/api/",P="51418271-3ce051128b40e60140119ef7a";async function m(o,t,i){const s={key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:i};return(await q.get(B,{params:s})).data}const f=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".load-more"),$=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:i,largeImageURL:s,tags:e,likes:r,views:n,comments:x,downloads:S})=>`
      <li class="gallery-item">
        <a href="${s}">
          <img class="gallery-image" src="${i}" alt="${e}" />
        </a>
        <div class="info">
          <p class="text"><b class="title-text">Likes:</b> ${r}</p>
          <p class="text"><b class="title-text">Views:</b> ${n}</p>
          <p class="text"><b class="title-text">Comments:</b> ${x}</p>
          <p class="text"><b class="title-text">Downloads:</b> ${S}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()}function M(){f.innerHTML=""}function b(){g.classList.remove("is-hidden")}function L(){g.classList.add("is-hidden")}function w(){h.classList.remove("is-hidden-btn")}function u(){h.classList.add("is-hidden-btn")}const O=document.querySelector(".form"),R=document.querySelector(".load-more");let l="",a=1;const d=15;let p=0;O.addEventListener("submit",async o=>{if(o.preventDefault(),l=o.currentTarget.elements["search-text"].value.trim(),a=1,!l){c.warning({message:"Please enter a search query!",position:"topRight"});return}M(),u(),b();try{const t=await m(l,a,d);if(p=t.totalHits,t.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t.hits),d*a<p&&w()}catch(t){c.error({message:"Oops! Something went wrong. Try again later.",position:"topRight"}),console.error(t)}finally{L()}});R.addEventListener("click",async()=>{a+=1,b(),u();try{const o=await m(l,a,d);y(o.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),d*a>=p?(u(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}catch(o){c.error({message:"Failed to load more images.",position:"topRight"}),console.error(o)}finally{L()}});
//# sourceMappingURL=index.js.map
